/**
 * Tests for deploy command and wrangler deploy utilities
 *
 * Covers the pure parsing/config-generation logic used by
 * `billclaw deploy` (including --temporary preview mode).
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest"
import {
  generateDeployConfig,
  findD1IdByName,
  findKvIdByTitle,
  parseD1IdFromCreate,
  parseKvIdFromCreate,
  parseWorkerUrl,
  parseClaimUrl,
  parseClaimMinutes,
} from "../utils/wrangler.js"

const BASE_TOML = `name = "firela-bot"
main = "src/server/index.ts"
compatibility_date = "2025-09-15"

[assets]
directory = "dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "firela-bot-data"
database_id = "152e5c7f-90da-4256-b142-c6e36e3690f9"

[[kv_namespaces]]
binding = "CONFIG"
id = "95ccdd7ead584b34ac9efb6c16131d37"

[triggers]
crons = ["7 */6 * * *"]
`

describe("generateDeployConfig", () => {
  it("rewrites the D1 database_id and KV namespace id", () => {
    const config = generateDeployConfig(BASE_TOML, {
      databaseId: "11111111-2222-3333-4444-555555555555",
      kvNamespaceId: "abc123def456",
      stripCrons: false,
    })

    expect(config).toContain(
      'database_id = "11111111-2222-3333-4444-555555555555"',
    )
    expect(config).toContain('id = "abc123def456"')
    // Old developer-account IDs must be gone
    expect(config).not.toContain("152e5c7f")
    expect(config).not.toContain("95ccdd7e")
  })

  it("keeps non-target fields intact", () => {
    const config = generateDeployConfig(BASE_TOML, {
      databaseId: "db-id",
      kvNamespaceId: "kv-id",
      stripCrons: false,
    })

    expect(config).toContain('name = "firela-bot"')
    expect(config).toContain('database_name = "firela-bot-data"')
    expect(config).toContain('binding = "CONFIG"')
    expect(config).toContain('crons = ["7 */6 * * *"]')
  })

  it("strips cron schedules when requested (temporary preview mode)", () => {
    const config = generateDeployConfig(BASE_TOML, {
      databaseId: "db-id",
      kvNamespaceId: "kv-id",
      stripCrons: true,
    })

    expect(config).toContain("crons = []")
    expect(config).not.toContain('crons = ["7 */6 * * *"]')
  })

  it("adds a generated-file header", () => {
    const config = generateDeployConfig(BASE_TOML, {
      databaseId: "db-id",
      kvNamespaceId: "kv-id",
      stripCrons: false,
    })

    expect(config.startsWith("# Generated by `billclaw deploy`")).toBe(true)
  })
})

describe("wrangler output parsers", () => {
  it("finds a D1 database by name in list output", () => {
    const output = `[
  { "uuid": "aaaa-bbbb", "name": "other-db", "created_at": "2026-01-01" },
  { "uuid": "cccc-dddd", "name": "firela-bot-data", "created_at": "2026-02-02" }
]`
    expect(findD1IdByName(output, "firela-bot-data")).toBe("cccc-dddd")
    expect(findD1IdByName(output, "missing-db")).toBeNull()
  })

  it("tolerates non-JSON preamble in list output", () => {
    const output = `Some warning text
[
  { "uuid": "aaaa-bbbb", "name": "firela-bot-data" }
]`
    expect(findD1IdByName(output, "firela-bot-data")).toBe("aaaa-bbbb")
  })

  it("finds a KV namespace by title in list output", () => {
    const output = `[
  { "id": "kv1", "title": "SOMETHING_ELSE" },
  { "id": "kv2", "title": "CONFIG" }
]`
    expect(findKvIdByTitle(output, "CONFIG")).toBe("kv2")
    expect(findKvIdByTitle(output, "NOPE")).toBeNull()
  })

  it("parses the database_id from d1 create output", () => {
    const output = `✅ Successfully created DB 'probe-db' in region APAC
{
  "d1_databases": [
    {
      "binding": "db",
      "database_name": "probe-db",
      "database_id": "4b57b016-77a0-44c8-b1bc-f2e70829236d"
    }
  ]
}`
    expect(parseD1IdFromCreate(output)).toBe(
      "4b57b016-77a0-44c8-b1bc-f2e70829236d",
    )
    expect(parseD1IdFromCreate("no id here")).toBeNull()
  })

  it("parses the namespace id from kv create output", () => {
    const output = `🌀 Creating namespace with title "CONFIG"
✨ Success!
{
  "kv_namespaces": [
    {
      "binding": "CONFIG",
      "id": "0d6e2adfe48a404db5199260d4ad6990"
    }
  ]
}`
    expect(parseKvIdFromCreate(output)).toBe("0d6e2adfe48a404db5199260d4ad6990")
  })

  it("parses ids from TOML-style wrangler output (wrangler 4.127 format)", () => {
    const kvOutput = `🌀 Creating namespace with title "CONFIG"
✨ Success!
To access your KV Namespace in your Worker, add this to your configuration file:
[[kv_namespaces]]
binding = "CONFIG"
id = "22300fb9da004d2d80c96ee7b7523682"`
    expect(parseKvIdFromCreate(kvOutput)).toBe(
      "22300fb9da004d2d80c96ee7b7523682",
    )

    const d1Output = `✅ Successfully created DB 'firela-bot-data' in region APAC
database_id = "ca87eb99-9f6f-4a4e-be0d-232c5978083d"`
    expect(parseD1IdFromCreate(d1Output)).toBe(
      "ca87eb99-9f6f-4a4e-be0d-232c5978083d",
    )
  })

  it("parses the workers.dev URL, claim URL, and claim window from deploy output", () => {
    const output = `Uploaded firela-bot (1.51 sec)
Deployed firela-bot triggers (1.37 sec)
  https://firela-bot.rounded-jar.workers.dev
Current Version ID: b40813b5

Claim within: 60 minutes
Claim URL: https://dash.cloudflare.com/claim-preview?claimToken=abc.def_123`

    expect(parseWorkerUrl(output)).toBe(
      "https://firela-bot.rounded-jar.workers.dev",
    )
    expect(parseClaimUrl(output)).toBe(
      "https://dash.cloudflare.com/claim-preview?claimToken=abc.def_123",
    )
    expect(parseClaimMinutes(output)).toBe(60)
  })

  it("returns null claim values for non-temporary deploy output", () => {
    const output = `Deployed firela-bot triggers
  https://firela-bot.example.workers.dev`
    expect(parseClaimUrl(output)).toBeNull()
    expect(parseClaimMinutes(output)).toBeNull()
  })

  it("prefers the id inside the kv_namespaces snippet over decoy id fields", () => {
    const output = `Account id = "should-not-match"
🌀 Creating namespace with title "CONFIG"
✨ Success!
[[kv_namespaces]]
binding = "CONFIG"
id = "real-id-123"`
    expect(parseKvIdFromCreate(output)).toBe("real-id-123")
  })

  it("parses the workers.dev URL even when the line has leading symbols", () => {
    const output = `Uploaded firela-bot
🚀 https://firela-bot.example.workers.dev (1.37 sec)`
    expect(parseWorkerUrl(output)).toBe(
      "https://firela-bot.example.workers.dev",
    )
  })
})

// Command-level tests with mocked wrangler utilities
import { deployCommand } from "./deploy.js"
import { createMockCliContext } from "../__tests__/test-utils.js"
import {
  deployUiWorker as deployUiWorkerMock,
  runCommand as runCommandMock,
} from "../utils/wrangler.js"

vi.mock("../utils/cloudflare.js", () => ({
  getMonorepoRoot: vi.fn(() => "/mock/monorepo-root"),
}))
vi.mock("../utils/wrangler.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../utils/wrangler.js")>()
  return {
    ...actual,
    deployUiWorker: vi.fn(),
    runCommand: vi.fn(),
  }
})
vi.mock("../utils/progress.js", () => ({
  Spinner: {
    withLoading: vi.fn(async (_text: string, fn: () => Promise<unknown>) => {
      return fn()
    }),
  },
}))
vi.mock("../utils/format.js", () => ({
  success: vi.fn(),
  error: vi.fn(),
  warn: vi.fn(),
  info: vi.fn(),
}))

describe("deploy command", () => {
  beforeEach(() => {
    vi.clearAllMocks()
    vi.mocked(runCommandMock).mockResolvedValue({
      code: 0,
      stdout: "",
      stderr: "",
    })
  })

  afterEach(() => {
    vi.restoreAllMocks()
  })

  it("should have correct command definition", () => {
    expect(deployCommand.name).toBe("deploy")
    expect(deployCommand.description).toBeDefined()
    expect(deployCommand.options).toBeDefined()
    expect(deployCommand.options?.[0]?.flags).toBe("--temporary")
  })

  it("builds then deploys in normal mode by default", async () => {
    vi.mocked(deployUiWorkerMock).mockResolvedValue({
      workerUrl: "https://firela-bot.example.workers.dev",
      configPath: "/mock/packages/ui/wrangler.deploy.toml",
    })

    await deployCommand.handler(createMockCliContext())

    expect(runCommandMock).toHaveBeenCalledWith(
      "pnpm",
      ["build"],
      "/mock/monorepo-root",
    )
    expect(deployUiWorkerMock).toHaveBeenCalledWith({ temporary: false })
  })

  it("passes temporary mode through and prints the claim URL", async () => {
    const consoleSpy = vi.spyOn(console, "log").mockImplementation(() => {})
    vi.mocked(deployUiWorkerMock).mockResolvedValue({
      workerUrl: "https://firela-bot.rounded-jar.workers.dev",
      claimUrl: "https://dash.cloudflare.com/claim-preview?claimToken=tok",
      claimMinutes: 60,
      configPath: "/mock/packages/ui/wrangler.deploy.toml",
    })

    await deployCommand.handler(createMockCliContext(), { temporary: true })

    expect(deployUiWorkerMock).toHaveBeenCalledWith({ temporary: true })
    expect(consoleSpy).toHaveBeenCalledWith(
      expect.stringContaining("claimToken=tok"),
    )

    consoleSpy.mockRestore()
  })
})
